{% set name = "teneto" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wiheto/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: b74daefe65c34f200b292eb3cd21d67f357fbd892c7b678c35e772af2b1eb1a2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - pytest-runner
  run:
    - python >={{ python_min }}
    - nilearn >=0.6.0
    - pybids >=0.11.1
    - statsmodels >=0.8.0
    - networkx >=2.0
    - python-louvain >=0.13
    - pandas >=0.21
    - scipy >=1.4.1
    - numpy >=1.19.5
    - templateflow >=0.6.2
    - matplotlib-base

test:
  imports:
    - teneto
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
    - pytest

about:
  home: https://github.com/wiheto/teneto
  summary: 'Temporal network tools'
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mediocretech
